### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nook24** [qwerji/nixie-clock#1]
Hi @qwerji 
I really love it! Could you please add License information to the repository?

PS: That's the nixie clock on my desk
![img_2883](https://user-images.githubusercontent.com/9019992/52860320-6806a280-312f-11e9-9936-a50bc6b68f58.JPG)

**Comment by qwerji** [comment]
I'm glad you like it! Cool clock. Added the License.
Thanks,
-Ben

**Comment by nook24** [comment]
Many thanks!
